### ISSUE TITLE
Datasheet 

### ISSUE THREAD

**Issue by flowersnlyrics** [analogdevicesinc/ad5940-examples#4]
I know this code is supposed to be used instead of a datasheet, but since this code still has TODOs, commented code and recursion, is there any document that can be more clear?

**Comment by neoanalog** [comment]
The official documents are datasheet and user guide on wiki. Check the Readme file, section Useful links.
Most of the code is already verified but it's still not perfect and we keep working on this.

**Comment by flowersnlyrics** [comment]
Thank you I missed that!
